### ISSUE TITLE
JSON output formatting

### ISSUE THREAD

**Issue by jjkoehorst** [BackofenLab/CRISPRidentify#13]
When using the JSON option the output format seems to be scrambled in some way.

For example:

```
"4265926   ......................  GGG                                                      s:0 i:0 d:0\n4265951   .........C..T.-T..--C.  CCCTTCCCTAAGAGGGAAGGGGGCTGGGGGGTTAGGTCTCTTTTTCAAACA      s:4 i:0 d:3\n4266021   ...........A..........                                                           s:1 i:0 d:0\n____________________________________________________________________________________________________\n          GGAATAAATATCGTTGCTGTAC 
```

Is if I read correctly an entry from the results folder but it is just one long string and all sub elements are glued together. Is this how it supposed to be?

**Comment by Alexander-Mitrofanov** [comment]
I believe that you look at the key "dot_representation" which contains a text representation of the array. This can be used to write an array to a file in a human-readable way and then manually inspect it. The same representation is used in the results folder.

You can use different keys to access the array in the json. For example "list_repeats", "list_spacers", "start", "end".

Please feel free to suggest a representation that is useful for you. We are still working on the improvements of CRISPRidentify.

Best,
Alex

**Comment by jjkoehorst** [comment]
Thanks for quick reply, we are currently investigating to use this method for high throughput genome annotation and to store the results in a graph database. Making it machine readable is therefore an important aspect that would make life a lot easier. Ill try my best to come with some recommendations. 

In addition I just had a look at the FASTa file output and the headers correspond to the CRISPR region containing multiple spacer/repeats and of course we can calculate the exact position of each spacer or repeat but it would be great if that could be added to the header of the fasta entry.

```
>NC_019693_CRISPR_1_3497269_3497448_repeat_1 START=3497269 END=3497307 SCORE= and other values?
TGTTTCAATCCCTGATAGGGATTAGAGGTTATTGAGAC START=... END=... 
>NC_019693_CRISPR_1_3497269_3497448_repeat_2 etc...
AGTTTCAATCCCTGATAGGGATTAGAGGTTATTGAGAC
```
