### ISSUE TITLE
Conda installation

### ISSUE THREAD

**Issue by sarah872** [BackofenLab/CRISPRidentify#2]
Hi,
I'm failing in installing the environment, even when removing all builds from the environment.
Do you have any idea what I could try?

**Comment by amri2k** [comment]
Hi Sarah,
I just tried and works fine for me. Let me ask, what kind of operating system do you have? and could share with us the errors?

Best, Omer

**Comment by sarah872** [comment]
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by amri2k** [comment]
- What is the error message that you got?
- miniconda version?

**Comment by sarah872** [comment]
I am using conda version 4.8.3.

This are the commands I am running:
```
git clone https://github.com/BackofenLab/CRISPRidentify
cd CRISPRidentify/
conda env create -f environment.yml
```

I put the error messages in the attached log file (there are a lot of conflicts...)
[conda.log](https://github.com/BackofenLab/CRISPRidentify/files/5747592/conda.log)


Thank you!

**Comment by Alexander-Mitrofanov** [comment]
The new environment has been released
