### ISSUE TITLE
No CRISPRidentify.py command

### ISSUE THREAD

**Issue by Shild94** [BackofenLab/CRISPRidentify#4]
Hi,

Thanks for providing such a powerful tool!
I installed it according to the suggested command "conda env create -f environment.yml", and finished successfully. However, I can not execute "python CRISPRidentify.py" after activating the environment. Indeed, I can not find this command "CRISPRidentify.py" in all the directories either. Could you kindly help to address this problem?
Thank you very much in advance.

Best,
Ling-Dong

**Comment by Alexander-Mitrofanov** [comment]
Hi Ling-Dong,

Please make sure that you downloaded the repository.
Then execute the command from the main folder. Please note that this folder has to have the CRISPRidentify.py script.
Feel free to ask more questions if you still have troubles.

Best,
Alex
