### ISSUE TITLE
CRISPRidentify.py must be run from CRISPRidentify directory only

### ISSUE THREAD

**Issue by EricDeveaud** [BackofenLab/CRISPRidentify#7]
Hello.

if ones try to run `CRISPRidentify.py` it must be in the same directory than `CRISPRidentify.py`

egg 
```(crispr_identify_env) > python3.7 CRISPRidentify.py    
No input was provided
Elapsed time:  2.193450927734375e-05
(crispr_identify_env) > cd ../
(crispr_identify_env) > python3.7 foo/CRISPRidentify.py  
Traceback (most recent call last):
  File "CRISPRidentify/CRISPRidentify.py", line 13, in <module>
    from pipeline import Pipeline
ModuleNotFoundError: No module named 'pipeline'
```

this is due to the way PYTHONPATH is handled
following patch allows to run from anywhere

```
--- CRISPRidentify.py.ori   2021-06-21 17:41:51.922067095 +0000
+++ CRISPRidentify.py   2021-06-21 17:46:53.788085259 +0000
@@ -10,7 +10,8 @@
 import subprocess
 import warnings
 warnings.filterwarnings("ignore")
-sys.path.insert(0, 'components/')
+dir_path = os.path.dirname(os.path.realpath(__file__))
+sys.path.insert(0, os.path.join(dir_path, 'components/'))
 from pipeline import Pipeline
 from components_ml import ClassifierWrapper
 import shutil
```

regards

Eric

**Comment by Alexander-Mitrofanov** [comment]
Hello Eric,

Thanks a lot for you suggestion and contribution to the CRISPRidentify project.
I find you idea valid and will modify the tool accordingly shortly.

Best,
Alex

**Comment by EricDeveaud** [comment]
I had commited this patch based on previous version in order to fix the tools and data use.
not really elegant but it works
maybee there's some kind of stuff to grab from .

[fix_tools_path.patch.txt](https://github.com/BackofenLab/CRISPRidentify/files/6732704/fix_tools_path.patch.txt)

**Comment by Alexander-Mitrofanov** [comment]
fixed now
