### ISSUE TITLE
allow CRISPRidentify to be run from anywhere :: not just archive dir

### ISSUE THREAD

**Issue by EricDeveaud** [BackofenLab/CRISPRidentify#8]
Hello, 

I was trying to install CRISPRidentify using standard unix conventions
and allow our users to ru it from anywhere.

tools and dspecific data tools path are broken as theyt are hard coded path relative to the archive tree. egg
`tools/vmatch/vmatch`  tool hardcoded
`tools/prodigal/prodigal` tool hardcoded
`tools/hmm_search/hmmsearch --tblout result_hmm.out tools/hmm_search/models_tandem.hmm protein_results.fa` hmme and model hardcoded
`tools/hmm_search/models_tandem.hmm` data hardcoded

tools and data shoul be searched relative to the install directory. 

regards

Eric

**Comment by Alexander-Mitrofanov** [comment]
Hello Eric

The vmatch, prodigal and hmmsearch tools are now used with the conda env as you suggested. The binaries for these tools were removed. 
I will fix the hardcoded paths to the models shortly. Thanks for the suggestion.

Best,
Alex

**Comment by Alexander-Mitrofanov** [comment]
fixed now
